Adding basic charm library
canonical/pgbouncer-operator pull request #1
Opened 2022-02-17 12:15 UTC by WRFitch

This PR creates a charm library that abstracts some common functions across the pgbouncer charms, which will be published to the /edge channel of the pgbouncer-operator charm on charmhub once implemented. 

The functions this library abstracts are as follows:
- Generating passwords
- Generating config files 

These will expand over time as the charms become more fully featured; specifically, generating pgbouncer.ini config files is going to become more sophisticated in future releases. 

[Jira Ticket](https://warthogs.atlassian.net/browse/DPE-48?atlOrigin=eyJpIjoiZjY4ZmNmZWI5YjhhNDNjMWIzMjE5Mjg2YWNiZDA0YzAiLCJwIjoiaiJ9)

2022-02-17 12:55 UTC, quiet-ranger requested changes

2022-02-17 12:55 UTC, quiet-ranger commented on lib/charms/dp_pgbouncer_operator/v0/pgb.py
> +def generate_password() -> str:
This function looks generic enough to me and useful to others.  We should consider extracting it to a generic library with security related functions.

2022-02-17 12:55 UTC, quiet-ranger commented on lib/charms/dp_pgbouncer_operator/v0/pgb.py
> +    return f"""[databases]
Do we plan to re-implement this with, say, templates?  It is understandable but somewhat difficult to read, especially if this is expected to grow with many more configuration items.

2022-02-17 12:55 UTC, quiet-ranger commented on lib/charms/dp_pgbouncer_operator/v0/pgb.py
> +    return "\n".join([f'"{username}" "{password}"' for username, password in users.items()])
This is a one liner using dictionary comprehension and a bit of string formatting.  Does it really need to be a separate function?

2022-02-17 12:55 UTC, quiet-ranger commented on tests/unit/test_pgb.py
> +        self.assertEqual(len(pw), 24)
Very good.  But can we also ensure that the resulting string contains only characters and digits?  Also, it would be good to write a comment in the implementation itself explaining why we made this choice and, for example, did not include some punctuation characters.

2022-02-17 12:55 UTC, quiet-ranger commented on tests/unit/test_pgb.py
> +        expected_pgb_ini = f"""[databases]
This implementation is fragile.  If someone changes the order or adds a new element in the implementation, the unit test will fail.  Please rethink this one.

2022-02-17 16:33 UTC, WRFitch commented on lib/charms/dp_pgbouncer_operator/v0/pgb.py
> +def generate_password() -> str:
This sounds useful. I'm also planning to abstract the encryption and hashing logic for pgbouncer authentication into this library, so perhaps this library can be abstracted once it's more than a single small function ;)

2022-02-17 16:38 UTC, WRFitch commented on lib/charms/dp_pgbouncer_operator/v0/pgb.py
> +    return "\n".join([f'"{username}" "{password}"' for username, password in users.items()])
I'd argue that because this string has to be formatted this exact way every time on both charms, extracting it into its own function is necessary. This way, it can also can be tested independently of any other charm function.

2022-02-17 16:39 UTC, WRFitch commented on tests/unit/test_pgb.py
> +        expected_pgb_ini = f"""[databases]
As Jon suggested above, I've replaced this with a string constant that is formatted during the test.

2022-02-17 17:56 UTC, quiet-ranger requested changes

2022-02-17 17:56 UTC, quiet-ranger commented on lib/charms/dp_pgbouncer_operator/v0/pgb.py
> +        A random 24-character string of letters and numbers.
Is the choice of only letters or numbers coming from a requirements document?  Is there a reason why we do not include punctuation characters, for example?   A simple clarifying comment is enough. If in doubt, we can ask around to see if there are any specific guidelines on this.

My objective here is not to be picky but to avoid it being bounced back further down the line.  Remember that the code is fully open sourced.

2022-02-17 17:59 UTC, quiet-ranger commented
As for the integration test failure, I see the following in the logs:

    raise JujuConnectionError('Model not found: {}'.format(model_name))
juju.errors.JujuConnectionError: Model not found: admin/itest

Could it be that it works locally because you created the model by hand but, in the integration tests, it does not exist yet?

2022-02-18 14:06 UTC, MiaAltieri reviewed
Looks _amazing_ just some knits

2022-02-18 14:06 UTC, MiaAltieri commented on tests/unit/test_pgb.py
> +        expected_userlist = '''"test1" "pw1"
is it possible to do `expected_userlist = '''"test1" "pw1"\n"test2" "pw2"'''` if so it would look nicer here :)

2022-02-18 14:06 UTC, MiaAltieri commented on lib/charms/dp_pgbouncer_operator/v0/pgb.py
> +            continue
I'd add a `logger` message if we skip a line due to incorrect formatting of the line.

2022-02-18 15:19 UTC, WRFitch commented on lib/charms/dp_pgbouncer_operator/v0/pgb.py
> +            continue
Good call, I've added a line of logging that states that if this is called, it's unable to parse a line in the userlist file. Unfortunately that line itself obviously can't be logged, since it contains a password, so it can't be too descriptive.

2022-02-18 16:56 UTC, WRFitch commented on .github/workflows/ci.yaml
> +      #     model: testing
To fix/replicate the integration testing issue, I've had to disable the part of the integration testing command that sets a model name, making this section unusable. However, there will also be a lot of changes to this section in future since this isn't a k8s charm and therefore shouldn't use microk8s for its integration testing. Therefore, I've left this content commented in and will update it in the next PR that provides a basic implementation for this charm.

2022-02-22 12:02 UTC, quiet-ranger approved these changes
Well done! To me this looks ready to be merged

2022-02-24 13:04 UTC, MiaAltieri reviewed
Looks great! One suggestion

2022-02-24 13:04 UTC, MiaAltieri commented on tests/unit/test_pgb.py
> +        userlist = inspect.cleandoc(
I see what you're saying about keeping it as a constant, since its so test specific and I agree. Would be possible to put these contents in a file `tests/unit/data/userlist.txt` and then do: 

```
        with open("tests/unit/data/userlist.txt") as f:
            userlist = f.read()
```

2022-02-24 13:05 UTC, MiaAltieri commented on tests/unit/test_pgb.py
> +        userlist = inspect.cleandoc(
I see what you're saying about keeping it as a constant, since its so test specific and I agree. Would be possible to put these contents in a file `tests/unit/data/userlist.txt` and then do: 

```
        with open("tests/unit/data/userlist.txt") as f:
            userlist = f.read()
```

2022-02-24 13:08 UTC, paulomach approved these changes
LGTM

2022-02-25 10:00 UTC, WRFitch commented on tests/unit/test_pgb.py
> +        userlist = inspect.cleandoc(
Thanks, I've added this in

2022-02-25 13:41 UTC, merged