Feature/auto charmhub publish
canonical/pgbouncer-operator pull request #12
Opened 2022-07-07 20:31 UTC by paulomach

## Proposal

Auto publish to charmhub latest/edge github workflow.
Charmhub access key added in repository secrets.

2022-07-08 08:03 UTC, jnsgruk submitted a review, later dismissed

2022-07-08 11:16 UTC, WRFitch requested changes
Pipeline looks great, thanks for submitting this Paulo! 

I'm currently not comfortable with releasing the charm even on /edge, since it currently doesn't work. Once PRs #10 and #13 are merged, the relations should be fully functional, and I'll be happy to merge this

2022-07-18 06:04 UTC, delgod approved these changes

2022-09-12 13:19 UTC, WRFitch commented
Update on this PR, we're now waiting on PRs #18 and #19, and then I'm happy to sort out merge conflicts and get this merged in :)

2022-09-13 12:45 UTC, marceloneppel commented on .github/workflows/release.yaml
> +      - integration-test-lxd
Looks good to be merged after the other two PRs that Will commented. Just a reminder: before merging this PR, this line should be changed (and also some jobs need to be added):
```suggestion
      - integration-standalone
      - integration-backend
      - integration-legacy-relations
```

2022-09-13 13:33 UTC, marceloneppel approved these changes
Looks great!

2022-09-13 15:37 UTC, WRFitch approved these changes

2022-09-13 16:10 UTC, merged