Added status badges
canonical/pgbouncer-operator pull request #165
Opened 2024-02-23 17:36 UTC by a-velasco

## Issue
This repo's status is not displayed in the [Charm Engineering Releases](https://releases.juju.is/?team=Data) overview.

## Solution
Added workflow badges for 
* CharmHub
* Release
* Tests

2024-02-23 20:15 UTC, dragomirp approved these changes

2024-02-27 08:40 UTC, taurus-forever requested changes
Dejavu... I have replied this already... somewhere... but cannot find.
We are using `1/stable` for pgbouncer VM, please update links as `latest/stable` belongs to legacy charm. Tnx!

2024-02-27 12:53 UTC, a-velasco commented
@taurus-forever I think the charmhub badge unfortunately only renders for the default charmhub address, so something like `https://charmhub.io/pgbouncer?channel=1/stable` won't work. We can merge it as is, and it should automatically update when we promote 1/stable to latest/stable (I'll make sure), or we can wait to merge.

2024-03-05 12:27 UTC, taurus-forever commented
OK, let's merge it AS IS as we plan to switch default one day soon anyway.

2024-03-05 12:28 UTC, taurus-forever approved these changes

2024-03-05 12:28 UTC, merged