[DPE-4772] Subordinate scale up
canonical/pgbouncer-operator pull request #274
Opened 2024-07-03 21:33 UTC by dragomirp

## Issue

## Solution

2024-07-04 10:59 UTC, dragomirp commented on src/relations/peers.py
> +            self.charm.client_relation.set_ready()
At this point we should have a backend relation, rendered user list and config, so unit should be ready

2024-07-04 10:59 UTC, dragomirp commented on src/relations/pgbouncer_provider.py
> +        event.relation.data[self.charm.unit].update({"state": "setup"})
Exact value doesn't really matter as long as it's not `ready`

2024-07-04 11:00 UTC, dragomirp commented on src/relations/pgbouncer_provider.py
> +        self.set_ready()
Setting the leader ready immediately, so we don't have to wait in a single unit cluster.

2024-07-04 11:02 UTC, dragomirp commented on src/relations/backend_database.py
> +            self.charm.peers.unit_databag.update({"backend_relation": str(self.relation.id)})
We can most probably remove some of the logic here to peer changed, but let's cleanup after we have the general behaviour right.

2024-07-04 20:48 UTC, marceloneppel commented on src/relations/pgbouncer_provider.py
> +        event.relation.data[self.charm.unit].update({"state": "setup"})
Testing with a patched `postgresql-test-app` charm (with the same changes in the `data_interfaces` library we have here), I found that this hook may fire after the client application receives the relation changed event.

Steps to reproduce:
```sh
juju model-config logging-config="<root>=INFO;unit=DEBUG"
juju deploy postgresql --channel 14/stable
cd ~/pgbouncer-operator
tox -e build-production
juju deploy ./pgbouncer_ubuntu-22.04-amd64.charm
cd ~/postgresql-test-app # It must contain the same changes in the `data_interfaces` library.
tox -e build-production
juju deploy ./postgresql-test-app_ubuntu-22.04-amd64.charm
juju relate pgbouncer postgresql-test-app:first-database
juju relate pgbouncer postgresql
```

Wait for the deployment to settle, then run the following commands:
```sh
juju add-unit postgresql-test-app
juju debug-log -m lxd:dev --include unit-postgresql-test-app-1 --include unit-pgbouncer-1 --replay
```

In the debug logs, you can see that the relation-changed event fires in the client application earlier than the relation-created event in the PgBouncer unit.
```sh
…
unit-postgresql-test-app-1: 20:24:39 INFO juju.worker.uniter.operation ran "first-database-relation-created" hook (via hook dispatching script: dispatch)
…
unit-postgresql-test-app-1: 20:24:42 DEBUG unit.postgresql-test-app/1.juju-log first-database:6: No provider units are available.
unit-postgresql-test-app-1: 20:24:42 INFO juju.worker.uniter.operation ran "first-database-relation-changed" hook (via hook dispatching script: dispatch)
…
unit-postgresql-test-app-1: 20:25:07 INFO unit.postgresql-test-app/1.juju-log first-database:6: database created at 2024-07-04 20:25:07.984376
…
unit-postgresql-test-app-1: 20:25:08 INFO juju.worker.uniter.operation ran "first-database-relation-changed" hook (via hook dispatching script: dispatch)
…
unit-pgbouncer-1: 20:25:10 INFO juju.worker.uniter.operation ran "database-relation-created" hook (via hook dispatching script: dispatch)
…
unit-postgresql-test-app-1: 20:25:10 DEBUG unit.postgresql-test-app/1.juju-log first-database:6: Subordinate provider unit not ready.
…
unit-pgbouncer-1: 20:25:20 INFO unit.pgbouncer/1.juju-log backend-database:7: database created at 2024-07-04 20:25:20.936335
…
```

The status logs also show something that confirms that (`juju show-status-log postgresql-test-app/1 -n 1000`):
```sh
…
04 Jul 2024 20:25:07Z  juju-unit  executing    running first-database-relation-changed hook for pgbouncer/1
04 Jul 2024 20:25:08Z  workload   active       received database credentials of the first database
…
```
And for PgBouncer (`juju show-status-log pgbouncer/1 -n 1000`):
```sh
…
04 Jul 2024 20:25:09Z  juju-unit  executing    running database-relation-created hook
…
```

2024-07-05 10:09 UTC, dragomirp commented on src/relations/pgbouncer_provider.py
> +        self.database_provides.set_subordinated(rel_id)
Set the app level flag. There's other synchronisation for existing units, so it should be safe even if not immediately set.

2024-07-05 10:09 UTC, dragomirp commented on src/relations/backend_database.py
> +            self.charm.client_relation.set_ready()
We should have the peer data and secret here already, so no need to retrigger the peer changed hook.

2024-07-05 12:56 UTC, marceloneppel approved these changes
LGTM!

2024-07-05 15:47 UTC, lucasgameiroborges approved these changes

2024-07-05 16:02 UTC, delgod requested changes

2024-07-05 16:59 UTC, dragomirp commented on src/relations/pgbouncer_provider.py
> +            relation.data[self.charm.unit].update({"state": "ready"})
`update_relation_data()` should be setting app level data, we need this in the unit databag. We'll need another helper for that.

2024-07-05 17:03 UTC, dragomirp commented on src/relations/pgbouncer_provider.py
> +            relation.data[self.charm.unit].update({"state": "ready"})
Possibly I can use [_update_relation_data_without_secrets()](https://github.com/canonical/data-platform-libs/blob/main/lib/charms/data_platform_libs/v0/data_interfaces.py#L1135-L1143) but that's private.

2024-07-05 17:23 UTC, juditnovak commented on src/relations/pgbouncer_provider.py
> +            relation.data[self.charm.unit].update({"state": "ready"})
No, we can't use any of those. Cross-charm relations (incl. all related internal functions) are restricted to `app` data.

Only peer relations support interface functions to access unit data at the moment.

2024-07-05 17:47 UTC, juditnovak commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +                is_subordinate = event.relation.data[key].get("subordinated") == "true"
Huh, this feels kinda hacky... I get the rationale, but I think we should have a proper "frame" around this.

The `DatabaseProviderEventHander` -- up to this point was not supposed to directly dig in databags.

We are reading an manipulating relation data via the `DatabaseProviderEventHander.relation_data`... Which --as for now-- strictly mean `app` level data.

We can alter the existing workflows to be ready to handle unit level data as well.
However that should go alongside considerations similar to the existing ones across the module (not just direct access in various parts of the code).

I could go with this solution as a temporary one, and I'm glad to volunteer to introduce the missing concept of handling unit level data in the libs. At that point this code will be cleaned up.

2024-07-05 18:21 UTC, dragomirp commented on lib/charms/data_platform_libs/v0/data_interfaces.py
> +                is_subordinate = event.relation.data[key].get("subordinated") == "true"
Let's keep it as is for the time being.

2024-07-05 19:25 UTC, delgod approved these changes

2024-07-08 14:03 UTC, merged