New Client Relation Tests
canonical/pgbouncer-operator pull request #34
Opened 2022-11-08 13:07 UTC by WRFitch

## Proposal
Adds integration tests for the new client relation

## Context
- Code is currently copied wholesale from the k8s charm

2022-11-15 19:40 UTC, marceloneppel requested changes
Nice!

2022-11-15 19:40 UTC, marceloneppel commented on tests/integration/relations/pgbouncer_provider/application-charm/metadata.yaml
> +    limit: 2
```suggestion
```

2022-11-15 19:40 UTC, marceloneppel commented on tests/integration/relations/pgbouncer_provider/helpers.py
> +            and/or alias.
```suggestion
            or if there is no data for the particular relation endpoint.
```

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/application-charm/requirements.txt
> +ops >= 1.5.3
TODO pin ops lib

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/application-charm/src/charm.py
> +        if event.params["readonly"]:
TODO mess with whitespace to make this more readable

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/helpers.py
> +async def run_sql_on_application_charm(
TODO verify this is necessary

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +    # check we can't write in readonly
TODO make these comments docstrings

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +# TODO revisit readonly function
TODO actually check this

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +                application_name=PG_2,
TODO these variable names are too similar - reconsider

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +# TODO revisit readonly function
TODO actually check this too

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +async def test_with_legacy_relation(ops_test: OpsTest):
TODO add a docstring explaining that I'm testing both relations simultaneously.

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +        ],  # ANOTHER_APPLICATION_APP_NAME], # TODO add back in once test is functional and off dev
TODO this

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +    assert application_connection_string != another_application_connection_string
TODO try if these connection strings actually work

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +    logger.error(await get_app_relation_databag(ops_test, pgb_unit_name, psql_relation.id))
TODO are these still necessary

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +    assert first_database_connection_string != second_database_connection_string
TODO check these actually work

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +        assert await check_relation_data_existence(
TODO update these to just get the databag

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +        assert await check_relation_data_existence(
TODO update these to just get the databag

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +        await scale_application(ops_test, PGB, 3)
TODO should be scaling pg, not pgb

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +        await scale_application(ops_test, PGB, 1)
TODO scale pg, not pgb

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +        # TODO check relation data was correctly removed from config
TODO do this

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +        )
TODO this can exist outside fast_forward

2022-11-22 13:49 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +        # TODO check relation data was correctly removed from config
TODO this can exist outside fast_forward

2022-11-22 13:52 UTC, paulomach reviewed
As we've talked, some fixes here and there as you noted, otherwise it's correct. Mark me for re-review after the updates

2022-11-22 13:52 UTC, paulomach commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +    logger.error(psql_databag)
remove this

2022-11-30 21:32 UTC, marceloneppel reviewed
Hey Will, I left some comments about some final changes.

2022-11-30 21:32 UTC, marceloneppel commented on src/relations/backend_database.py
> +        self.charm.peers.app_databag.pop(depart_flag, None)
I think this is unnecessary as the flag should be set only when a unit is being removed (so there won't be a next time this event is fired on that specific unit).

2022-11-30 21:32 UTC, marceloneppel commented on src/relations/backend_database.py
> +            self.charm.peers.app_databag.get(depart_flag, None) == "true"
Should it be the unit databag instead of the app databag? Or you can change the relation departed event to write the flag on the app databag as it also has a check for leader unit before the flag is set.

2022-11-30 21:32 UTC, marceloneppel commented on src/relations/pgbouncer_provider.py
> +            self.charm.peers.app_databag.pop(depart_flag, None)
Here we also have a mismatch of unit and app databags.

2022-11-30 21:32 UTC, marceloneppel commented on tests/unit/relations/test_backend_database.py
> +        logging.error(cfg.render())
This logging can be removed.

2022-11-30 21:32 UTC, marceloneppel commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +
Remove.

2022-11-30 21:32 UTC, marceloneppel commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +async def check_new_relation(ops_test: OpsTest):
This function probably can me moved to a helpers file.

2022-12-01 10:25 UTC, WRFitch commented on src/relations/backend_database.py
> +            self.charm.peers.app_databag.get(depart_flag, None) == "true"
you're right, I've updated everything to use the unit databag

2022-12-01 12:36 UTC, WRFitch commented on tests/integration/relations/pgbouncer_provider/test_pgbouncer_provider.py
> +    logger.error(psql_databag)
done :)

2022-12-08 12:48 UTC, paulomach approved these changes
superb

2022-12-08 13:34 UTC, merged